apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

nameSuffix: -dev
labels:
  - pairs:
      branch: dev
    includeSelectors: true
    includeTemplates: true
patches:
  - target:
      kind: Ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: seven-de
      spec:
        tls:
          - hosts:
            - dev.seven-spremberg.de
            secretName: "tls-dev-seven-de"
        rules:
         - host: dev.seven-spremberg.de
           http:
            paths:
              - pathType: Prefix
                path: /
                backend:
                  service:
                    name: svc-seven-de-dev
                    port:
                      name: http

